openapi: 3.0.0
info:
  title: TrialBalanceReport
  version: '1.0'
  description: trial balance report
  contact: iwork sparta-team
servers:
  - url: 'http://localhost:3000'
tags:
  - 
paths:
  /trial-balace-reports:
    get:
      summary: Fetchs all trial balance reports
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../models/TrialBalanceReport.v1.yaml
      operationId: get-trial-balace-reports
      description: Gets all trial balance reports
      tags:
        - Endpoints
    post:
      summary: ''
      operationId: post-trial-balace-reports
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/TrialBalanceReport.v1.yaml
      description: Add trial balance report
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/TrialBalanceReport.v1.yaml
      tags:
        - Endpoints
  '/trial-balace-reports/{12}':
    parameters:
      - schema:
          type: string
        name: '12'
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - Endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/TrialBalanceReport.v1.yaml
      operationId: get-trial-balace-reports-id
      description: Gets single trial balance report
    delete:
      summary: ''
      operationId: delete-trial-balace-reports-12
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/TrialBalanceReport.v1.yaml
      description: Remove trial balance report
      tags:
        - Endpoints
    put:
      summary: ''
      operationId: put-trial-balace-reports-12
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/TrialBalanceReport.v1.yaml
      description: Update trial balance report
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/TrialBalanceReport.v1.yaml
      tags:
        - Endpoints
components:
  schemas: {}
