openapi: 3.0.0
info:
  title: Accounts API
  version: '1.0'
  description: Manage Account List.
servers:
  - url: 'http://localhost:3000'
paths:
  /accounts:
    get:
      summary: Get Accounts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../models/Account.v1.yaml
      operationId: get-accounts
      description: Get Accounts
      tags:
        - Endpoints
    post:
      summary: Create Account
      tags:
        - Endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Account.v1.yaml
        '400':
          description: Bad Request
        '403':
          description: Forbidden
      operationId: post-accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/Account.v1.yaml
      description: Create Account
  '/accounts/{accountId}':
    parameters:
      - schema:
          type: string
        name: accountId
        in: path
        required: true
    get:
      summary: Get Account
      tags:
        - Endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Account.v1.yaml
        '404':
          description: Not Found
      operationId: get-accounts-accountId
      description: Get Account
    put:
      summary: Update Account
      tags:
        - Endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Account.v1.yaml
        '400':
          description: Bad Request
        '404':
          description: Not Found
      operationId: put-accounts-accountId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/Account.v1.yaml
      description: Update Account
    delete:
      summary: Remove Account
      tags:
        - Endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Account.v1.yaml
        '404':
          description: Not Found
      operationId: delete-accounts-accountId
      description: Delete Account
  /banks:
    get:
      summary: 'Get Banks '
      tags:
        - Endpoints
      responses: {}
      operationId: get-banks
    post:
      summary: Create Bank
      tags:
        - Endpoints
      responses: {}
      operationId: post-banks
components:
  schemas: {}
