openapi: 3.0.0
info:
  title: General Journal Report API
  version: '1.0'
  description: genral journal report api
  contact: iwork sparta-team
servers:
  - url: 'http://localhost:3000'
tags:
  - 
paths:
  /general-journal-reports:
    post:
      summary: Create General Journal Report
      tags:
        - Endpoints
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../../models/GeneralJournalReport.v1.yaml
      operationId: post-general-journal-reports
      description: Create a General Journal Report
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/GeneralJournalReport.v1.yaml
    get:
      summary: Get General Journal Reports
      tags:
        - Endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../models/GeneralJournalReport.v1.yaml
      operationId: get-general-journal-reports
      description: Get list of General Journal Reports
  '/general-journal-reports/{generalJournalReportId}':
    parameters:
      - schema:
          type: string
        name: generalJournalReportId
        in: path
        required: true
    get:
      summary: Get General Journal Report
      tags:
        - Endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/GeneralJournalReport.v1.yaml
      operationId: get-general-journal-reports-generalJournalReportId
      description: Get a General Journal Report
    delete:
      summary: Remove General Journal Report
      tags:
        - Endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/GeneralJournalReport.v1.yaml
        '404':
          description: Not Found
      operationId: delete-general-journal-reports-generalJournalReportId
      description: Remove a General Journal Report
    put:
      summary: Update General Journal Report
      tags:
        - Endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/GeneralJournalReport.v1.yaml
        '400':
          description: Bad Request
        '404':
          description: Not Found
      operationId: put-general-journal-reports-generalJournalReportId
      description: Update a General Journal Report
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/GeneralJournalReport.v1.yaml
components:
  schemas: {}
