openapi: 3.0.0
info:
  title: Asset-Category-API.v1
  version: '1.0'
  description: Asset category api
  contact: iwork sparta team
servers:
  - url: 'http://localhost:3000'
tags:
  - 
paths:
  /asset-categories:
    get:
      summary: Get asset collections
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/AssetCategory.v1.yaml
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      operationId: get-asset-categories
      description: Get asset-category collections
    post:
      summary: Add new asset category
      tags: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../../models/AssetCategory.v1.yaml
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      operationId: post-asset-categories
      description: Add new asset cateogry
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/AssetCategory.v1.yaml
  '/asset-categories/{categoryId}':
    parameters:
      - schema:
          type: string
        name: categoryId
        in: path
        required: true
    get:
      summary: Get single asset category
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/AssetCategory.v1.yaml
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      operationId: get-asset-categories-categoryId
      description: Get single asset category
    put:
      summary: Update asset category
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/AssetCategory.v1.yaml
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      operationId: put-asset-categories-categoryId
      description: 'Update asset category '
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/AssetCategory.v1.yaml
    delete:
      summary: Delete asset category
      tags: []
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      operationId: delete-asset-categories-categoryId
      description: Delete asset category
components:
  schemas: {}
