openapi: 3.0.0
info:
  title: VoucherLineAPI
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /voucher-lines:
    get:
      summary: Gets all voucher lines
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../models/VoucherLine.v1.yaml
      operationId: get-voucher-lines
    post:
      summary: ''
      operationId: post-voucher-lines
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/VoucherLine.v1.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/VoucherLine.v1.yaml
  '/voucher-lines/{12}':
    parameters:
      - schema:
          type: string
        name: '12'
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/VoucherLine.v1.yaml
      operationId: get-voucher-lines-id
components:
  schemas: {}
