openapi: 3.0.0
info:
  title: Partner
  version: '1.0'
  description: Manage list of partners.
  license:
    name: MIT
servers:
  - url: 'http://localhost:3000'
paths:
  /partners:
    get:
      summary: Get partners
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../models/Partner.v1.yaml
      operationId: get-partner
      description: Get a list of partners
      tags:
        - Endpoints
    post:
      summary: Create Partner
      tags:
        - Endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Partner.v1.yaml
        '400':
          description: Bad Request
        '403':
          description: Forbidden
      operationId: post-Partners
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/Partner.v1.yaml
        description: ''
      description: Create a partner
  '/partners/{partnerId}':
    parameters:
      - schema:
          type: string
        name: partnerId
        in: path
        required: true
    get:
      summary: Get Partner
      tags:
        - Endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Partner.v1.yaml
        '404':
          description: Not Found
      operationId: get-Partners-PartnerId
      description: Get a partner
    put:
      summary: Update Partner
      tags:
        - Endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Partner.v1.yaml
        '400':
          description: Bad Request
        '404':
          description: Not Found
      operationId: put-Partners-PartnerId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/Partner.v1.yaml
      description: Update a Partner
    delete:
      summary: Remove Partner
      tags:
        - Endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Partner.v1.yaml
        '404':
          description: Not Found
      operationId: delete-Partners-partnerId
      description: Delete a Partner
components:
  schemas: {}
