openapi: 3.0.0
info:
  title: Period
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /periods:
    get:
      summary: Get Period
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Period.v1.yaml
      operationId: get-period
      description: Get Period
      tags:
        - Endpoints
    post:
      summary: Create Period
      tags:
        - Endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Period.v1.yaml
        '400':
          description: Bad Request
        '403':
          description: Forbidden
      operationId: post-period
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Period.v1.yaml
      description: Create Period
  '/periods/{periodId}':
    parameters:
      - schema:
          type: string
        name: periodId
        in: path
        required: true
    get:
      summary: Get period
      tags:
        - Endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Period.v1.yaml
        '404':
          description: Not Found
      operationId: get-periods-periodId
      description: Get Period
    put:
      summary: Update Period
      tags:
        - Endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Period.v1.yaml
        '400':
          description: Bad Request
        '404':
          description: Not Found
      operationId: put-Period-periodId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Period.v1.yaml
      description: Update Period
    delete:
      summary: Remove Period
      tags:
        - Endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Period.v1.yaml
        '404':
          description: Not Found
      operationId: delete-Period-periodId
      description: Delete Period
components:
  schemas: {}
