openapi: 3.0.0
info:
  title: Invoice API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /invoices:
    get:
      summary: Fetches all invoices
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../models/Invoice.v1.yaml
      operationId: get-invoices
      description: Gets all invoices
      tags:
        - Endpoints
    post:
      summary: Create invoice
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Invoice.v1.yaml
      operationId: post-invoices
      description: Create an invoice
      tags:
        - Endpoints
  '/invoices/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Invoice.v1.yaml
      operationId: get-invoices-id
      description: Get single invoice
      tags:
        - Endpoints
    put:
      summary: ''
      operationId: put-invoices-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Invoice.v1.yaml
      description: Update invoice
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/Invoice.v1.yaml
      tags:
        - Endpoints
    delete:
      summary: ''
      operationId: delete-invoices-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Invoice.v1.yaml
      description: ''
      tags:
        - Endpoints
components:
  schemas: {}
