openapi: 3.0.0
info:
  title: InvoiceLineAPI
  version: '1.0'
  description: invoicing line api
  contact: iwork sparta-team
servers:
  - url: 'http://localhost:3000'
tags:
  - 
paths:
  /invoice-lines:
    get:
      summary: Fetches all invoice lines
      tags:
        - Invoice LIne
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../models/InvoiceLine.v1.yaml
      operationId: get-invoice-lines
      description: Gets all invoice lines
    post:
      summary: ''
      tags:
        - InvoiceLineAPI
      operationId: post-invoice-lines
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/InvoiceLine.v1.yaml
      description:  add new invoice line
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/InvoiceLine.v1.yaml
  '/invoice-lines/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - Invoice LIne
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Invoice.v1.yaml
      operationId: get-invoice-lines-id
      description: Gets single invoice line
    put:
      summary: ''
      operationId: put-invoice-lines-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/InvoiceLine.v1.yaml
      description: Update Invoice line
      tags:
        - Invoice LIne
    delete:
      summary: ''
      tags:
        - InvoiceLineAPI
      operationId: delete-invoice-lines-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/InvoiceLine.v1.yaml
      description: Remove Invoice line
components:
  schemas: {}
