openapi: 3.0.0
info:
  title: InvoiceLineAPI
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /invoice-lines:
    get:
      summary: Fetches all invoice lines
      tags:
        - Invoice LIne
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../models/InvoiceLine.v1.yaml
      operationId: get-invoice-lines
      description: Gets all invoice lines
    post:
      summary: ''
      operationId: post-invoice-lines
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/InvoiceLine.v1.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/InvoiceLine.v1.yaml
  /invoice-lines/12:
    parameters: []
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-invoice-lines-id
components:
  schemas: {}
