openapi: 3.0.0
info:
  title: Countries Api
  version: '1.0'
  license:
    name: MIT
  description: Manage country lists.
  contact: sparta-team
tags:
  - null
servers:
  - url: 'http://localhost:3000'
    description: Dev
paths:
  /countries:
    get:
      summary: List Countries
      description: Get all countries
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../models/Country.v1.yaml
      operationId: get-countries
    post:
      summary: Create Country
      description: Add new country
      tags: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../../models/Country.v1.yaml
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      operationId: post-countries
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/Country.v1.yaml
  '/countries/{countryId}':
    parameters:
      - schema:
          type: string
        name: countryId
        in: path
        required: true
    get:
      summary: Get Country
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  code:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                required:
                  - id
                  - name
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      operationId: get-countries-countryId
      description: Get single country info
    put:
      summary: Update Country
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Country.v1.yaml
      operationId: put-countries-countryId
      description: update company info
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/Country.v1.yaml
    delete:
      summary: Remove Country
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: delete-countries-countryId
      description: Delete company
components:
  schemas: {}
