openapi: 3.0.0
info:
  title: VoucherLineAPI
  version: '1.0'
  description: voucher line
  contact: iwork sparta-team
servers:
  - url: 'http://localhost:3000'
tags:
  - 
paths:
  /voucher-lines:
    get:
      summary: Gets all voucher lines
      tags:
        - Endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../models/VoucherLine.v1.yaml
      operationId: get-voucher-lines
      description: Get list of vouchers
    post:
      summary: ''
      operationId: post-voucher-lines
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/VoucherLine.v1.yaml
      description: Add new voucher
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/VoucherLine.v1.yaml
      tags:
        - Endpoints
  '/voucher-lines/{12}':
    parameters:
      - schema:
          type: string
        name: '12'
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - Endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/VoucherLine.v1.yaml
      operationId: get-voucher-lines-id
      description: Get voucehr
    put:
      summary: ''
      operationId: put-voucher-lines-12
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/VoucherLine.v1.yaml
      description: Update voucher line
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/VoucherLine.v1.yaml
      tags:
        - Endpoints
    delete:
      summary: ''
      operationId: delete-voucher-lines-12
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/VoucherLine.v1.yaml
      description: Delete voucher line
      tags:
        - Endpoints
components:
  schemas: {}
