openapi: 3.0.0
info:
  title: Tax-API.v1
  version: '1.0'
  description: tax api
  contact: iwork sparta team
servers:
  - url: 'http://localhost:3000'
tags:
  - 
paths:
  /taxes:
    get:
      summary: Get tax collection
      tags:
        - Tax
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Tax.v1.yaml
        '404':
          description: Not Found
      operationId: get-taxes
      description: Get tax collections
    post:
      summary: Add new tax
      tags:
        - Tax
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../../models/Tax.v1.yaml
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      operationId: post-taxes
      description: Add new tax
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/Tax.v1.yaml
  '/taxes/{taxId}':
    parameters:
      - schema:
          type: string
        name: taxId
        in: path
        required: true
    put:
      summary: Update a tax
      tags:
        - Tax
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Tax.v1.yaml
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      operationId: put-taxes-taxId
      description: Update a tax from collections
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/Tax.v1.yaml
    get:
      summary: Get a tax
      tags:
        - Tax
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Tax.v1.yaml
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      operationId: get-taxes-taxId
      description: Get a tax from collections
    delete:
      summary: Delete a tax
      tags:
        - Tax
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Tax.v1.yaml
        '404':
          description: Not Found
      operationId: delete-taxes-taxId
      description: Delete tax from tax collection
components:
  schemas: {}
