openapi: 3.0.0
info:
  title: Companies API
  version: '1.0'
  description: Manage Company List.
servers:
  - url: 'http://localhost:3000'
paths:
  /companies:
    get:
      summary: List Companies
      tags:
        - Endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../models/Company.v1.yaml
      operationId: get-companies
    post:
      summary: Create Company
      tags:
        - Endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Company.v1.yaml
        '400':
          description: Bad Request
      operationId: post-companies
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/Company.v1.yaml
  '/companies/{companyId}':
    parameters:
      - schema:
          type: integer
        name: companyId
        in: path
        required: true
    put:
      summary: Upadate Company
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Company.v1.yaml
        '400':
          description: Bad Request
        '404':
          description: Not Found
      operationId: put-companies-companyId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/Company.v1.yaml
      tags:
        - Endpoints
    delete:
      summary: Remove Company
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Company.v1.yaml
        '404':
          description: Not Found
      operationId: delete-companies-companyId
      tags:
        - Endpoints
    get:
      summary: Get Company
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Company.v1.yaml
        '404':
          description: Not Found
      operationId: get-companies-companyId
      description: ''
      tags:
        - Endpoints
components:
  schemas: {}
